#!/bin/bash
if ! ( echo "quit" | mariadb ); then
  mariadbd-safe &
  while ! ( echo "quit" | mariadb ); do
    echo "Waiting for MariaDB to start..."
    sleep 1
  done
fi
if [ ! -e /prenacs/docker/db_created ]; then
  mariadb -u root -prootpass < /prenacs/docker/create_db.sql && \
  touch /prenacs/docker/db_created
fi
